### ISSUE TITLE
Firefox WebExtensions support?

### ISSUE THREAD

**Issue by ghost** [Mati365/reddit-news#1]
Hi! I'd love to know if support for new Firefox's [WebExtensions](http://www.arewewebextensionsyet.com/) API is on the roadmap, and whether pull requests of porting effort are welcome. Thanks!

**Comment by Mati365** [comment]
Yes, the extension code is designed to use multiple platforms(there is platform folder) so porting it to firefox should not be a problem. I'll add some cool features(like notifications and built-in browser) and then I'll port it to firefox

**Comment by Mati365** [comment]
Done :)
